package com.coinbase.walletlink.models

/**
 * Represents a WalletLink session. A `Session` is created once a user scans a WalletLInk QR code
 *
 * @property sessionId Session ID generated by the host
 * @property secret Secret used to encrypt/decrypt data between guest and host
 */
data class Session(val sessionId: String, val secret: String)