platform :ios, '11.0'

target 'WalletLink' do
  pod 'CBHTTP', git: 'git@github.com:CoinbaseWallet/CBHTTP.git', commit: "a616dfe10ee470fe1c0fb19fa605a142f634612a"
  pod 'CBStore', git: 'git@github.com:CoinbaseWallet/Stores.git', commit: "444c4d462a91068729f245852fd111be5261f78c"
  pod 'CBCrypto', git: 'git@github.com:CoinbaseWallet/CBCrypto.git', commit: "3c3b3c0b1ea6ba502342f624df758df47ab0a56c"
  pod 'CBCore', git: 'git@github.com:CoinbaseWallet/CBCore.git', commit: "ee30448572da06ad1b060956b782360ea829b425"
  pod 'RxSwift', '~> 4.4.0'
  pod 'RxCocoa', '~> 4.4.0'
  pod 'Starscream', '~> 3.1'
  pod 'SwiftLint'
  pod 'SwiftFormat/CLI', '0.37.2'
  pod 'BigInt',  '~> 3.1.0'
end
