// Copyright (c) 2018-2019 Coinbase, Inc. <https://coinbase.com/>
// Licensed under the Apache License, version 2.0

package com.coinbase.walletlink.models

import java.net.URL

/**
 * Represents a WalletLink session. A `Session` is created once a user scans a WalletLInk QR code
 *
 * @property id Session ID generated by the host
 * @property secret Secret used to encrypt/decrypt data between guest and host
 * @property url WalletLink server websocket URL
 * @property version WalletLink server version
 * @property dappName name that initiated the new wallet link connection
 * @property dappImageURL image that initiated the new wallet link connection
 * @property dappURL URL that initiated the new wallet link connection
 */
data class Session(
    val id: String,
    val secret: String,
    val url: URL,
    val version: String? = null,
    val dappName: String? = null,
    val dappImageURL: URL? = null,
    val dappURL: URL? = null
)
